//! The [`Lane`] trait: one generic description of an unsigned integer lane.
//!
//! Before 0.4.5-buildfix2 every transform existed three times (`*_u16`, `*_u32`, `*_u64`).
//! The trait captures the handful of primitive operations those copies differed in, so each
//! algorithm is now written once and monomorphized per lane (no run-time dispatch, no cost).

/// Prevents implementations of [`Lane`] outside this crate; the NUM1 wire format only defines
/// 16-, 32- and 64-bit lanes.
mod sealed {
    /// Private supertrait of [`super::Lane`].
    pub trait Sealed {}
}

/// An unsigned little-endian integer lane (`u16`, `u32` or `u64`).
///
/// Signed values (deltas) are represented by the associated [`Lane::Signed`] type and converted
/// by *bit reinterpretation*: wrapping arithmetic on the unsigned lane equals wrapping arithmetic
/// on its two's-complement signed twin, so algorithms can compute in the unsigned ring and
/// reinterpret only at the boundary.
pub trait Lane:
    sealed::Sealed + Copy + Ord + Default + Eq + std::fmt::Debug + Send + Sync + 'static
{
    /// Two's-complement signed type of the same width.
    type Signed: Copy + Default + Eq + std::fmt::Debug + Send + Sync + 'static;
    /// Lane width in bits.
    const BITS: u8;
    /// Lane width in bytes.
    const BYTES: usize;
    /// Error message for a bit width larger than the lane.
    const WIDTH_TOO_LARGE: &'static str;
    /// Error message for a non-zero value packed with zero bit width.
    const NONZERO_AT_ZERO_WIDTH: &'static str;
    /// Error message for a value that does not fit the requested bit width.
    const VALUE_TOO_WIDE: &'static str;

    /// `self - other` modulo `2^BITS`.
    fn wrapping_sub(self, other: Self) -> Self;
    /// `self + other` modulo `2^BITS`.
    fn wrapping_add(self, other: Self) -> Self;
    /// Reinterprets the bits as the signed twin.
    fn to_signed(self) -> Self::Signed;
    /// Reinterprets signed bits as the unsigned lane.
    fn from_signed(value: Self::Signed) -> Self;
    /// ZigZag-maps a signed value: `0→0, -1→1, 1→2, -2→3, …`.
    fn zigzag(value: Self::Signed) -> Self;
    /// Inverse of [`Lane::zigzag`].
    fn unzigzag(self) -> Self::Signed;
    /// Zero-extends the lane to `u64`.
    fn to_u64(self) -> u64;
    /// Truncates a `u64` to the lane (keeps the low `BITS` bits).
    fn from_u64_truncating(value: u64) -> Self;
    /// Sign-extends a signed lane value to `i64`.
    fn signed_to_i64(value: Self::Signed) -> i64;
    /// Reads one lane from the first `BYTES` bytes of `chunk` (little-endian).
    fn read_le(chunk: &[u8]) -> Self;
    /// Writes the lane into the first `BYTES` bytes of `out` (little-endian).
    fn write_le(self, out: &mut [u8]);
}

/// Implements [`Lane`] for one unsigned/signed pair; the bodies are identical for every width,
/// which is exactly the duplication the trait removes from the algorithms.
macro_rules! impl_lane {
    ($unsigned:ty, $signed:ty) => {
        /// Marks the lane as one of the three NUM1 widths.
        impl sealed::Sealed for $unsigned {}

        /// Lane implementation generated by `impl_lane!`.
        impl Lane for $unsigned {
            /// See [`Lane::Signed`].
            type Signed = $signed;
            /// See [`Lane::BITS`].
            const BITS: u8 = <$unsigned>::BITS as u8;
            /// See [`Lane::BYTES`].
            const BYTES: usize = std::mem::size_of::<$unsigned>();
            /// See [`Lane::WIDTH_TOO_LARGE`].
            const WIDTH_TOO_LARGE: &'static str =
                concat!(stringify!($unsigned), " bit width exceeds lane width");
            /// See [`Lane::NONZERO_AT_ZERO_WIDTH`].
            const NONZERO_AT_ZERO_WIDTH: &'static str = concat!(
                "non-zero ",
                stringify!($unsigned),
                " value cannot use zero bit width"
            );
            /// See [`Lane::VALUE_TOO_WIDE`].
            const VALUE_TOO_WIDE: &'static str =
                concat!(stringify!($unsigned), " value exceeds selected bit width");

            #[inline(always)]
            /// See [`Lane::wrapping_sub`].
            fn wrapping_sub(self, other: Self) -> Self {
                <$unsigned>::wrapping_sub(self, other)
            }
            #[inline(always)]
            /// See [`Lane::wrapping_add`].
            fn wrapping_add(self, other: Self) -> Self {
                <$unsigned>::wrapping_add(self, other)
            }
            #[inline(always)]
            /// See [`Lane::to_signed`].
            fn to_signed(self) -> $signed {
                self as $signed
            }
            #[inline(always)]
            /// See [`Lane::from_signed`].
            fn from_signed(value: $signed) -> Self {
                value as $unsigned
            }
            #[inline(always)]
            /// See [`Lane::zigzag`].
            fn zigzag(value: $signed) -> Self {
                ((value << 1) ^ (value >> (<$unsigned>::BITS - 1))) as $unsigned
            }
            #[inline(always)]
            /// See [`Lane::unzigzag`].
            fn unzigzag(self) -> $signed {
                ((self >> 1) as $signed) ^ (-((self & 1) as $signed))
            }
            #[inline(always)]
            /// See [`Lane::to_u64`].
            fn to_u64(self) -> u64 {
                self as u64
            }
            #[inline(always)]
            /// See [`Lane::from_u64_truncating`].
            fn from_u64_truncating(value: u64) -> Self {
                value as $unsigned
            }
            #[inline(always)]
            /// See [`Lane::signed_to_i64`].
            fn signed_to_i64(value: $signed) -> i64 {
                value as i64
            }
            #[inline(always)]
            /// See [`Lane::read_le`].
            fn read_le(chunk: &[u8]) -> Self {
                let mut bytes = [0u8; std::mem::size_of::<$unsigned>()];
                bytes.copy_from_slice(&chunk[..std::mem::size_of::<$unsigned>()]);
                <$unsigned>::from_le_bytes(bytes)
            }
            #[inline(always)]
            /// See [`Lane::write_le`].
            fn write_le(self, out: &mut [u8]) {
                out[..std::mem::size_of::<$unsigned>()].copy_from_slice(&self.to_le_bytes());
            }
        }
    };
}

impl_lane!(u16, i16);
impl_lane!(u32, i32);
impl_lane!(u64, i64);

/// Decodes every complete little-endian lane of `input`; trailing bytes are ignored.
pub fn read_lanes<T: Lane>(input: &[u8]) -> Vec<T> {
    input.chunks_exact(T::BYTES).map(T::read_le).collect()
}

/// Serializes lanes back to little-endian bytes (inverse of [`read_lanes`]).
pub fn write_lanes<T: Lane>(values: &[T]) -> Vec<u8> {
    let (bytes, _) = write_lanes_from_iter(values.len(), values.iter().copied());
    bytes
}

/// Serializes at most `count` lanes produced by `values` into a pre-sized buffer.
///
/// Returns the buffer (always `count * BYTES` long, zero-filled past the last value) and the
/// number of values actually written, so callers can detect a short iterator.
pub fn write_lanes_from_iter<T: Lane>(
    count: usize,
    values: impl Iterator<Item = T>,
) -> (Vec<u8>, usize) {
    let mut out = vec![0u8; count * T::BYTES];
    let mut written = 0usize;
    for (chunk, value) in out.chunks_exact_mut(T::BYTES).zip(values) {
        value.write_le(chunk);
        written += 1;
    }
    (out, written)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Constants and conversions agree for every lane.
    #[test]
    fn lane_constants_and_conversions() {
        assert_eq!((u16::BITS, u16::BYTES), (16, 2));
        assert_eq!((<u32 as Lane>::BITS, u32::BYTES), (32, 4));
        assert_eq!((<u64 as Lane>::BITS, u64::BYTES), (64, 8));
        assert_eq!(u16::from_signed(-1i16), u16::MAX);
        assert_eq!(u32::MAX.to_signed(), -1i32);
        assert_eq!(u16::from_u64_truncating(0x1_2345), 0x2345);
        assert_eq!(<u32 as Lane>::signed_to_i64(-5), -5i64);
    }

    /// Lane I/O is little-endian and round-trips.
    #[test]
    fn lane_io_roundtrip() {
        let values = vec![1u32, 0xAABB_CCDD, u32::MAX];
        let bytes = write_lanes(&values);
        assert_eq!(&bytes[4..8], &[0xDD, 0xCC, 0xBB, 0xAA]);
        assert_eq!(read_lanes::<u32>(&bytes), values);
        assert_eq!(
            read_lanes::<u64>(&bytes[..11]).len(),
            1,
            "partial lanes are ignored"
        );
    }
}
