//! Large-file hardening (ACE 0.4.6, release CI only — `cargo test --release -- --ignored`).
//!
//! * 1 GiB streamed through the bounded-memory encoder and decoder, verified by SHA-256 of
//!   the reconstructed stream, with a constant source buffer;
//! * 256 MiB with indexed range reads past 2^28 (u64 offsets, index size, block count).
//!
//! Inputs are generated on the fly, so neither test keeps the source in memory.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)] // test code: a panic is a failing test

use std::fs::{self, File};
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::PathBuf;

use ace_core::{AceConfig, DecodeLimits};
use ace_corpus::Workload;
use ace_engine::AceIndexedDecoder;
use ace_stream::{compress_reader_known_size, decompress_stream, StreamLimits};
use sha2::{Digest, Sha256};

/// Period of the generated pattern.
const CHUNK: usize = 1024 * 1024;

/// Deterministic, unbounded byte source: `chunk[p % CHUNK] ^ (p / CHUNK) as u8`.
struct Generated {
    /// One MiB of the mixed workload.
    chunk: Vec<u8>,
    /// Next position.
    position: u64,
    /// Total bytes to produce.
    total: u64,
}

impl Generated {
    /// Source of `total` bytes.
    fn new(total: u64) -> Self {
        Self {
            chunk: Workload::Mixed.generate(CHUNK),
            position: 0,
            total,
        }
    }

    /// Byte at absolute position `p`.
    fn byte_at(&self, p: u64) -> u8 {
        self.chunk[(p % CHUNK as u64) as usize] ^ (p / CHUNK as u64) as u8
    }
}

impl Read for Generated {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        let remaining = (self.total - self.position).min(buf.len() as u64) as usize;
        for (offset, slot) in buf[..remaining].iter_mut().enumerate() {
            *slot = self.byte_at(self.position + offset as u64);
        }
        self.position += remaining as u64;
        Ok(remaining)
    }
}

/// `Write` sink that only hashes.
struct HashSink(Sha256, u64);

impl Write for HashSink {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0.update(buf);
        self.1 += buf.len() as u64;
        Ok(buf.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

/// Unique temporary file path for this test process.
fn temp_path(name: &str) -> PathBuf {
    std::env::temp_dir().join(format!("ace-0.4.6-{name}-{}.ace", std::process::id()))
}

/// Streams `total` generated bytes into a temporary ACE file and returns its path.
fn compress_to_file(name: &str, total: u64) -> PathBuf {
    let path = temp_path(name);
    let writer = BufWriter::new(File::create(&path).unwrap());
    let config = AceConfig::default();
    let stats = compress_reader_known_size(
        Generated::new(total),
        writer,
        total,
        config.clone(),
        StreamLimits::default(),
    )
    .unwrap();
    assert_eq!(stats.input_bytes, total);
    assert!(
        stats.peak_source_buffer_bytes <= config.block_size,
        "source buffer must stay bounded"
    );
    path
}

/// 1 GiB streaming round-trip verified through SHA-256.
#[test]
#[ignore = "release CI: 1 GiB streaming round-trip"]
fn streaming_one_gibibyte_roundtrip() {
    let total = 1024 * 1024 * 1024u64;
    let path = compress_to_file("1gib", total);
    let mut expected = HashSink(Sha256::new(), 0);
    std::io::copy(&mut Generated::new(total), &mut expected).unwrap();
    let mut actual = HashSink(Sha256::new(), 0);
    decompress_stream(
        BufReader::new(File::open(&path).unwrap()),
        &mut actual,
        DecodeLimits::default(),
    )
    .unwrap();
    fs::remove_file(&path).unwrap();
    assert_eq!(actual.1, total);
    assert_eq!(actual.0.finalize(), expected.0.finalize());
}

/// 256 MiB file: indexed reads near the end (offsets > 2^28) equal the generated bytes.
#[test]
#[ignore = "release CI: 256 MiB indexed file"]
fn indexed_reads_in_a_256_mib_file() {
    let total = 256 * 1024 * 1024u64;
    let path = compress_to_file("256mib", total);
    let reference = Generated::new(total);
    let mut decoder =
        AceIndexedDecoder::open(File::open(&path).unwrap(), DecodeLimits::default()).unwrap();
    assert_eq!(
        decoder.block_count() as u64,
        total / AceConfig::default().block_size as u64
    );
    for (start, length) in [
        (0u64, 4096u64),
        (total / 2 - 100, 200),
        (total - 70_000, 70_000),
        (total - 1, 1),
    ] {
        let bytes = decoder.read_range(start..start + length).unwrap();
        let expected: Vec<u8> = (start..start + length)
            .map(|p| reference.byte_at(p))
            .collect();
        assert_eq!(bytes, expected, "range {start}+{length}");
    }
    fs::remove_file(&path).unwrap();
}
