[package]
name = "ace-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "ace"
path = "src/main.rs"

[dependencies]
ace-codecs = { path = "../ace-codecs" }
ace-core = { path = "../ace-core" }
ace-engine = { path = "../ace-engine" }
ace-format = { path = "../ace-format" }
ace-index = { path = "../ace-index" }
ace-stream = { path = "../ace-stream" }
clap.workspace = true
anyhow.workspace = true

[lints]
workspace = true
