//! `ace-abprobe` — the measurement probe of the interleaved A/B comparison
//! (`tools/ace-ab0.5.0.py`).
//!
//! The probe is compiled **twice**, once against the baseline source tree and once against
//! the candidate tree, from a manifest generated by the A/B driver. It therefore uses only
//! the engine API both trees share (`compress`, `decompress`, `AceIndexedDecoder::read_range`)
//! and deliberately repeats the small Harness V3 calibration loop instead of depending on
//! `ace-bench`, which does not exist in older trees.
//!
//! ```text
//! ace-abprobe <case-id> <samples> <min-sample-ms> <warmups>
//! ```
//!
//! Prints one JSON object: case id, per-invocation samples (ns), iterations per sample,
//! processed bytes and an FNV-1a fingerprint of the produced output (the compressed file for
//! encode/decode cases, the returned bytes for range cases) used as byte-identity check.

use std::hint::black_box;
use std::io::Cursor;
use std::time::Instant;

use ace_core::{AceConfig, CompressionProfile, DecodeLimits};
use ace_corpus::Workload;
use ace_engine::{AceEngine, AceIndexedDecoder};

/// Boxed error type of the probe.
type ProbeError = Box<dyn std::error::Error>;

/// Size of every generated input.
const INPUT_BYTES: usize = 16 * 1024 * 1024;

/// Upper bound on invocations folded into one sample.
const MAX_ITERATIONS: u64 = 1 << 20;

/// The operation measured by one case.
enum Operation {
    /// `AceEngine::compress` of the whole input.
    Compress,
    /// `AceEngine::decompress` of the whole compressed file.
    Decompress,
    /// `AceIndexedDecoder::read_range(offset..offset + length)` on an open decoder.
    Range(u64, u64),
}

/// A fully specified A/B case.
struct Case {
    /// Corpus workload.
    workload: Workload,
    /// Engine profile.
    profile: CompressionProfile,
    /// Measured operation.
    operation: Operation,
}

/// Maps a stable case id onto its definition (ids match the `release-performance` family).
fn case(id: &str) -> Option<Case> {
    let (workload, profile, operation) = match id {
        "compression.fast.encode" => (
            Workload::Mixed,
            CompressionProfile::Fast,
            Operation::Compress,
        ),
        "compression.fast.decode" => (
            Workload::Mixed,
            CompressionProfile::Fast,
            Operation::Decompress,
        ),
        "compression.balanced.encode" => (
            Workload::Mixed,
            CompressionProfile::Balanced,
            Operation::Compress,
        ),
        "compression.balanced.decode" => (
            Workload::Mixed,
            CompressionProfile::Balanced,
            Operation::Decompress,
        ),
        "compression.dense.encode" => (
            Workload::Mixed,
            CompressionProfile::Dense,
            Operation::Compress,
        ),
        "compression.dense.decode" => (
            Workload::Mixed,
            CompressionProfile::Dense,
            Operation::Decompress,
        ),
        "numeric_fast.u32_counter.encode" => (
            Workload::U32Counter,
            CompressionProfile::Balanced,
            Operation::Compress,
        ),
        "numeric_fast.u32_counter.decode" => (
            Workload::U32Counter,
            CompressionProfile::Balanced,
            Operation::Decompress,
        ),
        "numeric_general.u64_timestamps.encode" => (
            Workload::U64TimestampsMs,
            CompressionProfile::Balanced,
            Operation::Compress,
        ),
        "numeric_general.delta_variable.encode" => (
            Workload::DeltaVariable,
            CompressionProfile::Balanced,
            Operation::Compress,
        ),
        "full_decompress.mixed" => (
            Workload::Mixed,
            CompressionProfile::Balanced,
            Operation::Decompress,
        ),
        "random_access.warm_64k" => (
            Workload::Mixed,
            CompressionProfile::Balanced,
            Operation::Range(3_000_000, 65_536),
        ),
        _ => return None,
    };
    Some(Case {
        workload,
        profile,
        operation,
    })
}

/// 64-bit FNV-1a over `bytes` (dependency-free output fingerprint).
fn fnv1a(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf2_9ce4_8422_2325, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x0100_0000_01b3)
    })
}

/// Runs `iterations` invocations and returns the total nanoseconds and the last output.
fn time_group<F>(operation: &mut F, iterations: u64) -> Result<(u64, Vec<u8>), ProbeError>
where
    F: FnMut() -> Result<Vec<u8>, ProbeError>,
{
    let start = Instant::now();
    for _ in 1..iterations {
        black_box(operation()?);
    }
    let output = operation()?;
    Ok((
        u64::try_from(start.elapsed().as_nanos()).unwrap_or(u64::MAX),
        output,
    ))
}

/// Warm-up, doubling calibration and `samples` timed samples (ns per invocation).
fn sample<F>(
    mut operation: F,
    samples: usize,
    min_sample_ns: u64,
    warmups: usize,
) -> Result<(Vec<u64>, u64, Vec<u8>), ProbeError>
where
    F: FnMut() -> Result<Vec<u8>, ProbeError>,
{
    for _ in 0..warmups {
        black_box(operation()?);
    }
    let mut iterations = 1u64;
    loop {
        let (elapsed, _) = time_group(&mut operation, iterations)?;
        if elapsed >= min_sample_ns || iterations >= MAX_ITERATIONS {
            break;
        }
        iterations *= 2;
    }
    let mut result = Vec::with_capacity(samples);
    let mut last = Vec::new();
    for _ in 0..samples {
        let (elapsed, output) = time_group(&mut operation, iterations)?;
        result.push(elapsed / iterations);
        last = output;
    }
    Ok((result, iterations, last))
}

/// Parses a positional argument.
fn arg<T: std::str::FromStr>(args: &[String], index: usize, name: &str) -> Result<T, ProbeError> {
    args.get(index)
        .and_then(|value| value.parse().ok())
        .ok_or_else(|| format!("missing or invalid <{name}>").into())
}

/// Entry point.
fn main() -> Result<(), ProbeError> {
    let args: Vec<String> = std::env::args().collect();
    let id: String = arg(&args, 1, "case-id")?;
    let samples: usize = arg(&args, 2, "samples")?;
    let min_sample_ms: u64 = arg(&args, 3, "min-sample-ms")?;
    let warmups: usize = arg(&args, 4, "warmups")?;
    let case = case(&id).ok_or_else(|| format!("unknown case id: {id}"))?;

    let data = case.workload.generate(INPUT_BYTES);
    let engine = AceEngine::new(AceConfig {
        profile: case.profile,
        threads: 1,
        ..AceConfig::default()
    })?;
    let min_sample_ns = min_sample_ms * 1_000_000;
    let (samples_ns, iterations, output, bytes) = match case.operation {
        Operation::Compress => {
            let (s, i, o) = sample(
                || Ok(engine.compress(&data)?),
                samples,
                min_sample_ns,
                warmups,
            )?;
            (s, i, o, data.len())
        }
        Operation::Decompress => {
            // Decode into one reused buffer (`decompress_from` exists in every 0.4.x tree), so
            // the measurement excludes page faults of a fresh 16 MiB vector per invocation.
            let encoded = engine.compress(&data)?;
            let mut buffer = Vec::with_capacity(data.len());
            let (s, i, _) = sample(
                || {
                    buffer.clear();
                    engine.decompress_from(Cursor::new(&encoded), &mut buffer)?;
                    Ok(Vec::new())
                },
                samples,
                min_sample_ns,
                warmups,
            )?;
            if buffer != data {
                return Err("decompression roundtrip mismatch".into());
            }
            (s, i, encoded, data.len())
        }
        Operation::Range(offset, length) => {
            let encoded = engine.compress(&data)?;
            let mut decoder =
                AceIndexedDecoder::open(Cursor::new(&encoded), DecodeLimits::default())?;
            let (s, i, o) = sample(
                || Ok(decoder.read_range(offset..offset + length)?),
                samples,
                min_sample_ns,
                warmups,
            )?;
            (s, i, o, length as usize)
        }
    };
    let samples_json: Vec<String> = samples_ns.iter().map(u64::to_string).collect();
    println!(
        "{{\"case_id\":\"{id}\",\"bytes\":{bytes},\"iterations_per_sample\":{iterations},\
         \"output_fnv1a\":\"{:016x}\",\"output_bytes\":{},\"samples_ns\":[{}]}}",
        fnv1a(&output),
        output.len(),
        samples_json.join(",")
    );
    Ok(())
}
