[package]
name = "ace-planner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ace-core = { path = "../ace-core" }
ace-cost = { path = "../ace-cost" }
ace-transforms = { path = "../ace-transforms" }
ace-codecs = { path = "../ace-codecs" }
ace-entropy = { path = "../ace-entropy" }

[dev-dependencies]
proptest.workspace = true
ace-analysis = { path = "../ace-analysis" }
