#!/usr/bin/env python3
"""ACE 0.4.6 code audit: unsafe placement and panic-policy inventory.

Checks (exit 1 on violation):

* ``unsafe`` appears only in the audited files (``UNSAFE_ALLOWED``), and every ``unsafe``
  block / impl is preceded by a ``// SAFETY:`` comment within six lines;
* every ``#[allow(clippy::...)]`` in production code (``crates/*/src`` outside ``#[cfg(test)]``
  modules) carries a justification comment on the same or the previous line.

Writes the generated ``docs/PANIC-AUDIT-0.4.6.md`` (``--write``).

usage: ace-code_audit0.4.6.py [--write]
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UNSAFE_ALLOWED = {
    "crates/ace-simd/src/avx2.rs",
    "crates/ace-simd/src/crc32c.rs",
    "crates/ace-simd/src/scan.rs",
    "crates/ace-bench/src/alloc.rs",
}
UNSAFE_USE = re.compile(r"\bunsafe\s*(\{|impl\b|fn\b)")
ALLOW = re.compile(r"#\[allow\((clippy::[a-z_]+(?:,\s*clippy::[a-z_]+)*)\)\]")
PANIC_LINTS = ("unwrap_used", "expect_used", "panic", "todo", "unimplemented")


def production_lines(path: pathlib.Path) -> list[tuple[int, str]]:
    """Numbered lines of ``path`` before its first ``#[cfg(test)]`` (tests are exempt)."""
    lines = []
    for number, line in enumerate(path.read_text().splitlines(), start=1):
        if line.strip().startswith("#[cfg(test)]"):
            break
        lines.append((number, line))
    return lines


def rust_sources() -> list[pathlib.Path]:
    """Every production Rust source of the workspace."""
    return sorted(ROOT.glob("crates/*/src/**/*.rs")) + sorted(ROOT.glob("crates/*/build.rs"))


def audit_unsafe(problems: list[str]) -> list[tuple[str, int, str]]:
    """Unsafe sites as ``(file, line, kind)``; appends policy violations to ``problems``."""
    sites = []
    for path in rust_sources():
        relative = path.relative_to(ROOT).as_posix()
        lines = path.read_text().splitlines()
        for index, line in enumerate(lines):
            code = line.split("//", 1)[0]
            match = UNSAFE_USE.search(code)
            if not match:
                continue
            kind = {"{": "block", "impl": "impl", "fn": "fn"}[match.group(1).split()[0]]
            sites.append((relative, index + 1, kind))
            if relative not in UNSAFE_ALLOWED:
                problems.append(f"{relative}:{index + 1}: unsafe outside the audited files")
            if kind in ("block", "impl"):
                context = "\n".join(lines[max(0, index - 6):index + 1])
                if "SAFETY:" not in context:
                    problems.append(f"{relative}:{index + 1}: unsafe {kind} without // SAFETY: comment")
    return sites


def audit_allows(problems: list[str]) -> list[tuple[str, int, str, str]]:
    """Production ``allow(clippy::..)`` sites as ``(file, line, lints, justification)``."""
    sites = []
    for path in rust_sources():
        relative = path.relative_to(ROOT).as_posix()
        numbered = production_lines(path)
        for position, (number, line) in enumerate(numbered):
            match = ALLOW.search(line)
            if not match:
                continue
            same = line.split("]", 1)[1] if "]" in line else ""
            previous = numbered[position - 1][1] if position else ""
            justification = (same.split("//", 1)[1] if "//" in same else
                             previous.strip().lstrip("/").strip() if previous.strip().startswith("//") else "")
            if not justification.strip():
                problems.append(f"{relative}:{number}: #[allow({match.group(1)})] without justification")
            sites.append((relative, number, match.group(1), justification.strip()))
    return sites


def render(allows: list[tuple[str, int, str, str]], unsafe_sites: list[tuple[str, int, str]]) -> str:
    """Markdown of the generated panic audit."""
    panic_allows = [site for site in allows if any(lint in site[2] for lint in PANIC_LINTS)]
    lines = [
        "# ACE 0.4.6 — Panic audit",
        "",
        "> Generated by `tools/ace-code_audit0.4.6.py --write`; do not edit by hand.",
        "",
        "## Policy",
        "",
        "`clippy::unwrap_used`, `expect_used`, `panic`, `todo`, `unimplemented` and `dbg_macro` are",
        "`deny` for every production crate (`[workspace.lints.clippy]`). Tests are exempt",
        "(`clippy.toml`: `allow-unwrap-in-tests`, `allow-expect-in-tests`, `allow-panic-in-tests`;",
        "integration tests carry an explicit file-level `allow`). The benchmark harness",
        "(`ace-bench`) is a measurement tool and may assert.",
        "",
        "## Panic-lint exceptions in production code",
        "",
        f"**{len(panic_allows)}** exception(s).",
        "",
    ]
    if panic_allows:
        lines += ["| Location | Lints | Justification |", "|---|---|---|"]
        lines += [f"| `{f}:{n}` | `{l}` | {j} |" for f, n, l, j in panic_allows]
        lines.append("")
    lines += ["## Other clippy allowances in production code", "",
              "| Location | Lints | Justification |", "|---|---|---|"]
    lines += [f"| `{f}:{n}` | `{l}` | {j} |" for f, n, l, j in allows if (f, n, l, j) not in panic_allows]
    lines += ["", "## `unsafe` inventory (details: `docs/UNSAFE-AUDIT-0.4.6.md`)", "",
              "| Location | Kind |", "|---|---|"]
    lines += [f"| `{f}:{n}` | {k} |" for f, n, k in unsafe_sites]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    """Run the audit; with ``--write`` regenerate the Markdown report."""
    problems: list[str] = []
    unsafe_sites = audit_unsafe(problems)
    allows = audit_allows(problems)
    if "--write" in argv:
        target = ROOT / "docs" / "PANIC-AUDIT-0.4.6.md"
        target.write_text(render(allows, unsafe_sites))
        print(f"written {target.relative_to(ROOT)}")
    print(f"unsafe sites: {len(unsafe_sites)} (all in audited files: {not any('outside' in p for p in problems)})")
    print(f"production clippy allowances: {len(allows)}")
    for problem in problems:
        print(f"AUDIT: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
